version: 2.1

orbs:
  win: circleci/windows@5.0 # The Windows orb gives you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor:
      name: win/default # executor type
      size: medium # can be medium, large, xlarge, 2xlarge

    steps:
      # Commands are run in a Windows virtual machine environment
      - checkout
      - run: Write-Host 'Hello, Windows'
      - run: echo "Starting"
      - run: dir
      - run: echo "Completed"
      - run: whoami
      - run: get-volume
      - run: |
          $Env:Path
      - run: |
          [System.Environment]::GetEnvironmentVariable("Path","Machine")
      - run: |
          [System.Environment]::GetEnvironmentVariable("Path","User")
      - run: |
          [System.Environment ]::GetEnvironmentVariable("Path","Process")
      - run: docker system info
      # Check if fast boot is enabled.
      - run: powercfg -a
